name             'sprout-rvm'
maintainer       'Al Jazeera America'
maintainer_email 'ajam-dev@aljazeera.net'
license          'MIT'
description      'Installs/Configures rvm'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.2'
supports         'mac_os_x'
depends          'sprout-base'
depends          'homebrew'
